### PR TITLE
Switch to https for URLs

### PR DESCRIPTION
**Pull request by m-allanson**
👋 This fixes mixed content warnings when viewing this page at https://www.gatsbyjs.org/packages/gatsby-source-trello/

### CODE REVIEW

**Comment by Necmttn** [comment]
Thank you :)

**Comment by m-allanson** [comment]
👋 thanks for merging this! Any chance you could publish a new version with the change included?

**Comment by Necmttn** [comment]
Sure will do,

**Comment by Necmttn** [comment]
https://www.npmjs.com/package/gatsby-source-trello updated.

**Comment by m-allanson** [comment]
Thanks! 🙏 🎉

**Pull request merged**
